### ISSUE TITLE
placeholder crash

### ISSUE THREAD

**Issue by vaniron** [happyzleaf/PokexpMultiplier#2] opened 2017-12-31 03:33 UTC
Hello,
found server crashing if placeholderapi is installed - i dont even use pixelmon variables in scoreboard. Can something be done about this? I tried multiple placeholderapi version without any success.
Crashlog: https://pastebin.com/raw/ZaJWkxVM

**Comment by hqppyz** [comment] 2017-12-31 13:23
The best thing i can do is to update it to PlaceholderAPI 4.4
Can you test this build and see if it works for you? 'Cause i can't reproduce your error
[pokexpmultiplier-1.1.5.zip](https://github.com/happyzleaf/PokexpMultiplier/releases)

**Comment by vaniron** [comment] 2017-12-31 18:33
Yup, looks like working. Thanks for updating.

**Comment by hqppyz** [comment] 2018-01-01 17:20
Closing

**Closed as completed by hqppyz** 2018-01-01 17:20 UTC
